# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f17e0442ee86d5b6f8a157932fa0cc7898f240c597956023a305c067a8a66a81c9a8895794c5bdc7710ed8faa2d19eea6acc4f07e2d4f513b1ea7991334bd58

test:
  secret_key_base: bdee1c117ea5ce09b0ba29d96a842d5f55c1600fbaf5965302a01f442ec2c8de565a9b932f528f7e3d09085bba39a9382cfefda716acc8e8937e0f0678a0ccd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
